lifelog:
  image: emag/lifelog
  volumes:
    - .:/tmp/project
  environment:
    _JAVA_OPTIONS: "-Dswarm.project.stage.file=file:///tmp/project/lifelog-project-stages.yml -Dswarm.project.stage=production"
  links:
    - lifelog-db:db
    - lifelog-auth:auth
  ports:
    - 8080:8080
lifelog-db:
  image: postgres:9.5.3
  environment:
    POSTGRES_USER: lifelog
    POSTGRES_PASSWORD: lifelog
lifelog-auth:
  image: jboss/keycloak:1.9.8.Final
  volumes:
    - .:/tmp/project
  command: -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/project/lifelog.json